### ISSUE TITLE
What's left to finish this off?

### ISSUE THREAD

**Issue by christianp** [limefrogyank/siunitx-pcc#21]
Hi,
A port of siunitx to MathJax v3 is sorely needed - thank you!
The README says that the project would be finished at the end of Summer 2023; I suppose that target was missed. Are you still working on this, or has the funding ended? 
Is there any documentation of what still needs to be done to get it production-ready?

**Comment by limefrogyank** [comment]
Sorry, I just noticed this comment.  I had it mostly done and was optimizing code to ensure it runs as quickly as possible.  You should be able to see what's left from the other issues.  I got distracted and was working on other things and haven't gotten back to this unfortunately.  Looks like one thing got broken in the refactoring:

![image](https://github.com/user-attachments/assets/df3a5d57-d0da-486d-b1ef-3e972cf01eca)

I haven't checked thoroughly yet, but looks like that's it.  

I would say that if you want to use it as a separate library, it's fairly ready (other than that one bug with angle symbol over decimal).  You can see how I integrated it into MathJax with the demo page.  Otherwise, there were plans to integrate it with MathJax directly, but that has to wait on truly finishing this and then having @dpvc sign off on it.

I can't make promises, but thanks for the nudge.  I'll see what I can do before the year's over.

**Comment by limefrogyank** [comment]
Ha, got it all done today :)

**Comment by limefrogyank** [comment]
#22 merged development to main

**Comment by christianp** [comment]
Great, thanks!

Can you add a licence, please?

**Comment by limefrogyank** [comment]
When I get a chance to do it on my pc, it will likely be the same as MathJax's.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by limefrogyank** [comment]
All done.

**Comment by christianp** [comment]
@limefrogyank thank you very much for this! I finally mustered up the courage to look at how to integrate this with Chirun, and it only took 5 minutes in the end!
